### ISSUE TITLE
Empty query operators does not return a result.

### ISSUE THREAD

**Issue by vaultec81** [dappkit/aviondb#11]
**Version**:
0.1.1
**Platform**:
NodeJS & Browser

**Describe the bug**
Methods using query operators should return all results. In order to get any results at all a query operator must be supplied.

**To Reproduce**
1. Run `Collection.find({})`, `collection.findOne({})` with an empty object as query.
2. Result is `[]` (an empty array) or `{}` (an empty object).

**Expected behavior**
Expected behavior for `Collection.find({})` should be a full array containing results, and `collection.findOne({})` should return the first object found. 

**Observed behavior**
Result is [] (an empty array) or {} (an empty object).

**Comment by vasa-develop** [comment]
fix: https://github.com/dappkit/aviondb/commit/46dee49b6f0737603d7d670baa1ea476cc4b8688
