### ISSUE TITLE
AvionDB Logo

### ISSUE THREAD

**Issue by apavlo** [dappkit/aviondb#13]
I've added AvionDB to my encyclopedia of databases:

https://dbdb.io/db/aviondb

Do you have a SVG logo for this system? Thanks.

-- Andy

**Comment by vaultec81** [comment]
SVG available [here](https://ipfs.io/ipfs/QmSPm7LwS6EzZw3aKkgSg4nFavAJSoGWG2U4fg7xkAZUa5)


Also country of origin is India and United States.

**Comment by vasa-develop** [comment]
Hi @apavlo 

We have updated the logo for AvionDB. Here are some samples. Feel free to update the logo on dbdb.io.

Thanks :)

![aviondb](https://user-images.githubusercontent.com/28847087/81482672-78d09600-9256-11ea-86cb-3a6a800c491e.png)
![logo](https://user-images.githubusercontent.com/28847087/81482673-7bcb8680-9256-11ea-8ddc-f6db54c22372.png)

**Comment by apavlo** [comment]
Do you have a SVG file of this?

**Comment by vasa-develop** [comment]
@apavlo yup. Here you go! [aviondb.svg](https://bafzbeiekuueascn2ltb23u4d3v2osrratsppwcur3ermbd2g6v62vmv56u.textile.space/aviondb.svg)

**Comment by apavlo** [comment]
I need the first one with the words "AvionDB" in it.

**Comment by vasa-develop** [comment]
@vaultec81 can you help us out here?

**Comment by vaultec81** [comment]
@apavlo Sorry for the delay. The full size SVG logo is available [here](https://ipfs.io/ipfs/QmPZULETmbfJG2Fa3wewjJUmySmzmDmxqbsG1FFKajsSpy)
