### ISSUE TITLE
Typescript Interfaces & ESLint Config

### ISSUE THREAD

**Issue by deanpress** [dappkit/aviondb#29]
It'd be great to see the AvionDB environment fully integrated with Typescript (interfaces for each class etc, strict types for method arguments etc).

I also noticed a lot of variables use `var` instead of `const` or `let`.  An ESLint config could help enforce some requirements (such as only use `const` or `let` instead of `var` , only allow arrow functions etc)

**Comment by vasa-develop** [comment]
@deanpress can you give me some references that would help me do this?

**Comment by deanpress** [comment]
@vasa-develop Most importantly we would need to set up an ESLint config + enforce a Typescript code style and compiler options (to compile to js for Node < 14 and browser). I'm working on a branch to get us started :)

**Comment by deanpress** [comment]
PR in progress: https://github.com/dappkit/aviondb/pull/31

**Comment by deanpress** [comment]
PR merged!
