### ISSUE TITLE
Release v0.1.0 🚀

### ISSUE THREAD

**Issue by vaultec81** [dappkit/aviondb#3]
### What's left for release
- [x] Update documentation to include latest API specs.
- [x] Create a change log. Although won't be used until later releases.
- [x] Add MIT license to readme and repo.
- [x] Different non-placeholder name for the project.
- [x] Add an Overview of the project Architecture & description in README
- [x] Add Usage section in README

Additional tasks:
- [x] Contributors & thank yous list
- [x] Contributing Guidelines
- [x] Code of Conduct
- [x] Create pre-release & test

### Estimated shipping date
Saturday the 18th of April

### General bugfixes and updates: 

Relevant PRs
* feat: add support for query operators (https://github.com/dappkit/ipfsdb/pull/2)
* refactor: optimise findOne method (https://github.com/dappkit/ipfsdb/pull/1)
* Create LICENSE (https://github.com/dappkit/ipfsdb/pull/4)

#### **This release is not finalized yet** additional changes prior to release may be added. Considerable amount of review is required before finalization.
Reviewers and contributions are welcome.

**Comment by vasa-develop** [comment]
### Pre-release

Use `npm install --save aviondb@next` to install

If this works ok, then we can do a final release

**Comment by vasa-develop** [comment]
### Released 🚀

Check it out [here](https://www.npmjs.com/package/aviondb). 

Thanks to the contributors:

- @vaultec81 
- @vasa-develop 

See [README](https://github.com/dappkit/aviondb/blob/master/README.md) for more info.
