### ISSUE TITLE
Further Typescript support

### ISSUE THREAD

**Issue by deanpress** [dappkit/aviondb#33]
Now that the next release is ported to Typescript, existing classes and methods should be properly typed and documented with jsdoc so that Intellisense can guide development. That should make working with AvionDB in VSCode a breeze!

**Comment by vasa-develop** [comment]
Here are some useful resources:
- [orbit-db typings](https://github.com/orbitdb/orbit-db-types)
- Related issue: https://github.com/orbitdb/orbit-db-types/issues/25
