### ISSUE TITLE
Sorting query results (cursor.sort())

### ISSUE THREAD

**Issue by deanpress** [dappkit/aviondb#34]
An essential part of collection management is the ability to sort documents by a field. See MongoDB `cursor.sort()` reference: https://docs.mongodb.com/manual/reference/method/cursor.sort/#cursor.sort

Example: `collection.find().sort( { "score" : -1 } )` finds all all entries in the collection and then sorts them by their `score` value in descending order (`1` for ascending and `-1` for descending).

This is an essential feature for AvionDB.

**Comment by vasa-develop** [comment]
PR: https://github.com/dappkit/aviondb/pull/38
