### ISSUE TITLE
[BUG]: Cannot list or get existing collection instance after dapp restart/refresh

### ISSUE THREAD

**Issue by vasa-develop** [dappkit/aviondb#9]
**Version**:

`0.1.1`

**Platform**:

NodeJS & Browser

**Describe the bug**
The way we track the open collections is not persistent.

**To Reproduce**
1. Create a collection named "users" in a browser.
2. Refresh the browser.
3. Try listing the collections using `db.listCollections()`. 
4. Try getting the instance of the previously created collection using `db.collection("users")`

**Expected behavior**
- Step 3 should list the previously created collections: `["users"]`
- Step 4 should return a "users" collection instance.

**Observed Behaviour**
- Step 3 gives an empty array: `[]` meaning no open collections.
- Step 4 throws error: `Collection: users is not open.`

**Comment by vaultec81** [comment]
Fixed in https://github.com/dappkit/aviondb/commit/72610ce5260fe63d8ab5c468ee52de2246bc0ac6 and https://github.com/dappkit/aviondb/commit/6121fe99e8226ed7dd1694fe29d46ead13a6a6a1
